### ISSUE TITLE
Trailing format delimiters should be kept in the result string

### ISSUE THREAD

**Issue by mmoo** [arthurdenner/format-string-by-pattern#184]
Hi,
Is this module still supported?

I think it works not as expected in the following case:
String to format: `123`
Pattern: `(999)`
AR: `(123`
ER:`(123)`

Please tell me what you think.
Thank you.

**Comment by arthurdenner** [comment]
Hi, @mmoo! 👋

You're correct, the library doesn't work in this case. It's not covered at the moment.

Would you be interested in supporting it?

**Comment by arthurdenner** [comment]
And could you say what is your use case to have the described pattern?

**Comment by arthurdenner** [comment]
So... I went ahead and tried it out, you can see it on the PR above. I've added test cases but they don't give so much confidence at the moment. Could you pull the branch and try it out and add other test cases for your usage? I'd really appreciate that.

**Comment by arthurdenner** [comment]
@mmoo, any updates from your side? Have you checked the PR?

**Comment by arthurdenner** [comment]
@mmoo, the linked PR is now merged and you can test it using `v1.2.1`.

Let me know if you find any issues.
