### ISSUE TITLE
Questions about using format-string-by-pattern with react-final-form

### ISSUE THREAD

**Issue by iloveip** [arthurdenner/format-string-by-pattern#3]
Hi there,

I would like to use `format-string-by-pattern` with `react-final-form` for masking inputs. But I have several questions.

1. Is it possible to escape characters to make an unremovable prefix in phone numbers? For example, `+7 (` in `+7 (999) 999-99-99`.
1. Is it possible to change mask character to `"_"` instead of white space?

**Comment by arthurdenner** [comment]
Hi @iloveip! :wave: 

Sorry for the wait to reply, but...

1. Right now, it is not. We only consider everything that is not a letter or a number to be a separator. Maybe you can control this with `react-final-form` itself, not allowing a value smaller than `+7 `? I'm not sure if that's possible and haven't tested, but maybe it is.

2. There is no masking in this library, we just modify the input based on the pattern and return it, so you can't tell it to render `_` in the missing spaces.

I'm very open to expand this library, so if you want to implement these features, feel free to submit PRs and I'll gladly review it.
